import { Property, Tenant, RentPayment, Expense, Document, Notification, DashboardStats, PropertyStatus, PaymentStatus, ExpenseCategory } from '@/types'

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    name: 'Downtown Apartments',
    address: '123 Main St, New York, NY 10001',
    type: 'residential',
    units: 12,
    rentAmount: 2500,
    image: 'https://images.unsplash.com/photo-1545324418-cc4dc30f37b5?w=800&h=600&fit=crop',
    status: PropertyStatus.ACTIVE,
    managerId: '2',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Westside Complex',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    type: 'residential',
    units: 8,
    rentAmount: 3000,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop',
    status: PropertyStatus.ACTIVE,
    managerId: '2',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Industrial Office Park',
    address: '789 Tech Drive, San Francisco, CA 94105',
    type: 'commercial',
    units: 4,
    rentAmount: 5000,
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop',
    status: PropertyStatus.ACTIVE,
    managerId: '2',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date(),
  },
]

export const MOCK_TENANTS: Tenant[] = [
  {
    id: '1',
    propertyId: '1',
    email: 'john.doe@email.com',
    name: 'John Doe',
    phone: '(555) 123-4567',
    leaseStartDate: new Date('2024-01-01'),
    leaseEndDate: new Date('2025-12-31'),
    rentAmount: 2500,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date(),
  },
  {
    id: '2',
    propertyId: '1',
    email: 'jane.smith@email.com',
    name: 'Jane Smith',
    phone: '(555) 234-5678',
    leaseStartDate: new Date('2023-06-01'),
    leaseEndDate: new Date('2025-05-31'),
    rentAmount: 2500,
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date(),
  },
  {
    id: '3',
    propertyId: '2',
    email: 'mike.johnson@email.com',
    name: 'Mike Johnson',
    phone: '(555) 345-6789',
    leaseStartDate: new Date('2024-02-15'),
    leaseEndDate: new Date('2026-02-14'),
    rentAmount: 3000,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date(),
  },
  {
    id: '4',
    propertyId: '2',
    email: 'sarah.wilson@email.com',
    name: 'Sarah Wilson',
    phone: '(555) 456-7890',
    leaseStartDate: new Date('2023-09-01'),
    leaseEndDate: new Date('2025-08-31'),
    rentAmount: 3000,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date(),
  },
]

export const MOCK_RENT_PAYMENTS: RentPayment[] = [
  {
    id: '1',
    tenantId: '1',
    propertyId: '1',
    amount: 2500,
    dueDate: new Date('2024-06-01'),
    paidDate: new Date('2024-05-28'),
    status: PaymentStatus.PAID,
    notes: 'Paid on time',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-05-28'),
  },
  {
    id: '2',
    tenantId: '1',
    propertyId: '1',
    amount: 2500,
    dueDate: new Date('2024-07-01'),
    paidDate: undefined,
    status: PaymentStatus.PENDING,
    createdAt: new Date('2024-07-01'),
    updatedAt: new Date(),
  },
  {
    id: '3',
    tenantId: '2',
    propertyId: '1',
    amount: 2500,
    dueDate: new Date('2024-06-01'),
    paidDate: new Date('2024-06-15'),
    status: PaymentStatus.PAID,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: '4',
    tenantId: '3',
    propertyId: '2',
    amount: 3000,
    dueDate: new Date('2024-05-01'),
    paidDate: undefined,
    status: PaymentStatus.OVERDUE,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date(),
  },
]

export const MOCK_EXPENSES: Expense[] = [
  {
    id: '1',
    propertyId: '1',
    category: ExpenseCategory.MAINTENANCE,
    amount: 1500,
    description: 'Roof repair and maintenance',
    date: new Date('2024-05-10'),
    createdBy: '2',
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date(),
  },
  {
    id: '2',
    propertyId: '1',
    category: ExpenseCategory.UTILITIES,
    amount: 850,
    description: 'Monthly utility bills',
    date: new Date('2024-06-05'),
    createdBy: '2',
    createdAt: new Date('2024-06-05'),
    updatedAt: new Date(),
  },
  {
    id: '3',
    propertyId: '2',
    category: ExpenseCategory.INSURANCE,
    amount: 2000,
    description: 'Annual property insurance',
    date: new Date('2024-04-15'),
    createdBy: '2',
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date(),
  },
  {
    id: '4',
    propertyId: '1',
    category: ExpenseCategory.PROPERTY_TAX,
    amount: 5000,
    description: 'Quarterly property tax payment',
    date: new Date('2024-03-30'),
    createdBy: '2',
    createdAt: new Date('2024-03-30'),
    updatedAt: new Date(),
  },
]

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: '1',
    propertyId: '1',
    tenantId: '1',
    name: 'Lease Agreement - Unit A',
    type: 'lease',
    url: 'https://example.com/lease-001.pdf',
    uploadedBy: '2',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date(),
  },
  {
    id: '2',
    propertyId: '1',
    name: 'Property Insurance Policy',
    type: 'receipt',
    url: 'https://example.com/insurance-policy.pdf',
    uploadedBy: '2',
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date(),
  },
  {
    id: '3',
    propertyId: '2',
    tenantId: '3',
    name: 'Lease Agreement - Unit B',
    type: 'lease',
    url: 'https://example.com/lease-002.pdf',
    uploadedBy: '2',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date(),
  },
]

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: '1',
    userId: '2',
    title: 'Rent Payment Overdue',
    description: 'Mike Johnson (Unit B2) has an overdue rent payment',
    type: 'warning',
    read: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: '2',
    userId: '2',
    title: 'New Expense Recorded',
    description: 'Maintenance expense of $1,500 recorded for Downtown Apartments',
    type: 'info',
    read: false,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: '3',
    userId: '3',
    title: 'Rent Payment Due Soon',
    description: 'Your rent payment is due on July 1st, 2024',
    type: 'info',
    read: true,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
]

export function getDashboardStats(): DashboardStats {
  return {
    totalProperties: MOCK_PROPERTIES.length,
    totalTenants: MOCK_TENANTS.length,
    totalRentCollected: 23500,
    pendingPayments: MOCK_RENT_PAYMENTS.filter(p => p.status === PaymentStatus.PENDING || p.status === PaymentStatus.OVERDUE).length,
    totalExpenses: MOCK_EXPENSES.reduce((sum, expense) => sum + expense.amount, 0),
  }
}
